Repository UniversityOfDundee-Computing/cw1-web-development-project-cryptologists-of-css, pull requests merged in 2025-02, with the labels that each got.

#6 Beth
  Test/styles.css
  legacy.html
  meeting_2_notes.md
Labels: help wanted

#26 Add the development.html file and add the Website Development Overview.xlsx file
  Website Development Overview.xlsx
  development.html
  legacy.html
Labels: enhancement

#29 I added a link at the bottom footer, and i re-added a picture which i…
  ABOUT_UPDATE_1.html
Labels: documentation

#63 Complete the Development Page
  development.html
  luyen/merged_styles.css
Labels: enhancement

#69 Add related videos
  development.html
  luyen/merged_styles.css
Labels: enhancement

#82 Added video-container style
  Test/styles.css
Labels: enhancement
